module.exports = {
    darkMode: false,
    purge: ["./public/**/*.html", "./src/**/*.{js,jsx,ts,tsx}"],
    theme: {
        borderRadius: {
            none: "0rem",
            DEFAULT: "0.5rem",
        },
        borderWidth: {
            none: "0rem",
            DEFAULT: "0.5rem",
        },
        colors: {
            // Light
            black: "#1f1f33",
            white: "#ffffff",

            primary: "#1f1f33",
            secondary: "#f6ffcc",
            secondary: "#d2e573",

            // Dark
            // white: "#1f1f33",
            // black: "#ffffff",
        },
        fontFamily: {
            sans: [
                '"Inter"',
                "ui-sans-serif",
                "system-ui",
                "-apple-system",
                "BlinkMacSystemFont",
                '"Segoe UI"',
                "Roboto",
                '"Helvetica Neue"',
                "Arial",
                '"Noto Sans"',
                "sans-serif",
                '"Apple Color Emoji"',
                '"Segoe UI Emoji"',
                '"Segoe UI Symbol"',
                '"Noto Color Emoji"',
            ],
            mono: [
                "ui-monospace",
                "SFMono-Regular",
                "Menlo",
                "Monaco",
                "Consolas",
                '"Liberation Mono"',
                '"Courier New"',
                "monospace",
            ],
        },
        fontSize: {
            xsmall: "0.625rem",
            small: "0.75rem",
            medium: "0.875rem",
            large: "1rem",
            xlarge: "1.25rem",
        },
        fontWeight: {
            regular: "400",
            bold: "800",
        },
        lineHeight: {
            small: "1.1",
            medium: "1.3",
            large: "1.5",
        },
        spacing: {
            0: "0rem",
            0.5: "0.25rem",
            1: "0.5rem",
            1.5: "0.75rem",
            2: "1rem",
            2.5: "1.25rem",
            3: "1.5rem",
            3.5: "1.75rem",
            4: "2rem",
            5: "2.5rem",
            6: "3rem",
            7: "3.5rem",
            8: "4rem",
            12: "6rem",
            16: "8rem",
            32: "16rem",
        },
    },
};
