module.exports = {
    darkMode: false,
    purge: ["./public/**/*.html", "./src/**/*.{js,jsx,ts,tsx}"],
    theme: {
        colors: {
            black: "#132240",
            white: "#ffffff",
            gray: {
                xlight: "#F5F7FA",
                light: "#C0C4CC",
                base: "#878D99",
                dark: "#6B7280",
                xdark: "#525866",
            },
            blue: {
                base: "#175ce5",
            },
            purple: {
                xlight: "#e5e5ff",
            },
            yellow: {
                xlight: "",
            },
        },
        fontFamily: {
            sans: [
                '"Fira Sans"',
                "ui-sans-serif",
                "system-ui",
                "-apple-system",
                "BlinkMacSystemFont",
                '"Segoe UI"',
                "Roboto",
                '"Helvetica Neue"',
                "Arial",
                '"Noto Sans"',
                "sans-serif",
                '"Apple Color Emoji"',
                '"Segoe UI Emoji"',
                '"Segoe UI Symbol"',
                '"Noto Color Emoji"',
            ],
            mono: [
                "ui-monospace",
                "SFMono-Regular",
                "Menlo",
                "Monaco",
                "Consolas",
                '"Liberation Mono"',
                '"Courier New"',
                "monospace",
            ],
        },
        fontSize: {
            xxsmall: "0.25rem",
            xsmall: "0.5rem",
            small: "0.75rem",
            base: "1rem",
            large: "1.25rem",
            xlarge: "1.5rem",
            xxlarge: "2rem",
        },
        fontWeight: {
            base: "500",
            bold: "800",
        },
        lineHeight: {
            narrow: "1.1",
            base: "1.3",
            tall: "1.5",
        },
        spacing: {
            0: "0rem",
            0.5: "0.25rem",
            1: "0.5rem",
            1.5: "0.75rem",
            2: "1rem",
            2.5: "1.25rem",
            3: "1.5rem",
            3.5: "1.75rem",
            4: "2rem",
            5: "2.5rem",
            6: "3rem",
            7: "3.5rem",
            8: "4rem",
            12: "6rem",
            16: "8rem",
            32: "16rem",
        },
    },
};
